name: Generate Snake Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate contribution graph
        uses: Ashutosh00710/github-contribution-snake-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: "github-contribution-snake.svg"
          snake_color: "00FFFF"   # neon color for snake
          background_color: "0A0A0A"
          width: 900
          height: 150
